# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='hi', unique=True),
            preserve_default=False,
        ),
    ]
