# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 21:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bullets',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
