# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160328_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='android',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='desktopapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='ios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='webapp',
            field=models.BooleanField(default=False),
        ),
    ]
