# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20160415_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='d', unique=True),
            preserve_default=False,
        ),
    ]
